# Generated by Django 6.0.4 on 2026-05-30 17:44

import django.db.models.deletion
import userdefinedmodel.models.node
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFieldValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_save', models.BooleanField(default=False)),
                ('admin_label', models.CharField(blank=True, max_length=200)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiFieldValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_save', models.BooleanField(default=False)),
                ('admin_label', models.CharField(blank=True, max_length=200)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80)),
                ('data_type', models.CharField(choices=[('text_short', 'Text Short'), ('text_long', 'Text Long'), ('text_markdown', 'Text Markdown'), ('text_richtext', 'Text Richtext'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime'), ('select_single', 'Select Single'), ('select_multi', 'Select Multi'), ('image', 'Image'), ('file', 'File'), ('user_select', 'User Select'), ('user_select_multi', 'User Select Multi'), ('group_select', 'Group Select'), ('group_select_multi', 'Group Select Multi'), ('submodel_select', 'Submodel Select'), ('submodel_list', 'Submodel List'), ('entity_select', 'Entity Select'), ('entity_select_multi', 'Entity Select Multi')], max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_localized', models.BooleanField(default=False)),
                ('type_config', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=userdefinedmodel.models.node.UUIDFilenameUploadTo('proposal_files'))),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('image_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiFieldRuleAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('source', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='TransitionAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('pre', 'Pre'), ('post', 'Post')], max_length=4)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserDefinedModelEntityNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllowedMimeTypesRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MaxFileSizeRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('max_bytes', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MaxItemsRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('max_items', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MaxLengthRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('max_length', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MaxValueRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('max_value', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MinItemsRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('min_items', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MinLengthRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('min_length', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MinValueRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('min_value', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('pattern', models.CharField(max_length=500)),
                ('failure_message', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='RequiredInLanguageRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
                ('language', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='RequiredRule',
            fields=[
                ('singlefieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.singlefieldvalidationrule')),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.singlefieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='AtLeastOneRequiredRule',
            fields=[
                ('multifieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.multifieldvalidationrule')),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.multifieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='ExactlyOneRequiredRule',
            fields=[
                ('multifieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.multifieldvalidationrule')),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.multifieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='MutualExclusionRule',
            fields=[
                ('multifieldvalidationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.multifieldvalidationrule')),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.multifieldvalidationrule',),
        ),
        migrations.CreateModel(
            name='BulkMigrationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('done', 'Done'), ('partial', 'Partial')], default='draft', max_length=10)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('total_entities', models.PositiveIntegerField(default=0)),
                ('done_entities', models.PositiveIntegerField(default=0)),
                ('failed_entities', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.configversion')),
                ('target_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.configversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multifieldvalidationrule',
            name='config_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_field_rules', to='userdefinedmodel.configversion'),
        ),
        migrations.CreateModel(
            name='EditGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddField(
            model_name='configversion',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='userdefinedmodel.fieldconfig'),
        ),
        migrations.AddField(
            model_name='singlefieldvalidationrule',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_field_rules', to='userdefinedmodel.fielddefinition'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='submodel_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_as_submodel', to='userdefinedmodel.configversion'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='userdefinedmodel.configversion'),
        ),
        migrations.CreateModel(
            name='BulkMigrationFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('map', 'Map'), ('discard', 'Discard')], max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='userdefinedmodel.bulkmigrationplan')),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.fielddefinition')),
                ('target_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.fielddefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldDefinitionTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='userdefinedmodel.fielddefinition')),
            ],
        ),
        migrations.AddField(
            model_name='multifieldvalidationrule',
            name='fields',
            field=models.ManyToManyField(related_name='multi_field_rules', through='userdefinedmodel.MultiFieldRuleAssociation', to='userdefinedmodel.fielddefinition'),
        ),
        migrations.AddField(
            model_name='multifieldruleassociation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_field_rule_associations', to='userdefinedmodel.fielddefinition'),
        ),
        migrations.AddField(
            model_name='multifieldruleassociation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='userdefinedmodel.multifieldvalidationrule'),
        ),
        migrations.CreateModel(
            name='SendNotificationAction',
            fields=[
                ('transitionaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.transitionaction')),
                ('recipients_config', models.JSONField(default=list)),
                ('subject_template', models.TextField(blank=True)),
                ('body_template', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.transitionaction',),
        ),
        migrations.CreateModel(
            name='SetFieldValueAction',
            fields=[
                ('transitionaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.transitionaction')),
                ('field_slug', models.CharField(max_length=80)),
                ('value_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.transitionaction',),
        ),
        migrations.CreateModel(
            name='TriggerChildTransitionAction',
            fields=[
                ('transitionaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.transitionaction')),
                ('child_transition_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.transitionaction',),
        ),
        migrations.CreateModel(
            name='SubmodelInstance',
            fields=[
                ('userdefinedmodelentitynode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.userdefinedmodelentitynode')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
            bases=('userdefinedmodel.userdefinedmodelentitynode',),
        ),
        migrations.CreateModel(
            name='UserDefinedModelEntity',
            fields=[
                ('userdefinedmodelentitynode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedmodel.userdefinedmodelentitynode')),
            ],
            options={
                'abstract': False,
            },
            bases=('userdefinedmodel.userdefinedmodelentitynode',),
        ),
        migrations.AddField(
            model_name='userdefinedmodelentitynode',
            name='config_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='userdefinedmodel.configversion'),
        ),
        migrations.AddField(
            model_name='userdefinedmodelentitynode',
            name='parent_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_nodes', to='userdefinedmodel.fielddefinition'),
        ),
        migrations.AddField(
            model_name='userdefinedmodelentitynode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='userdefinedmodel.userdefinedmodelentitynode'),
        ),
        migrations.CreateModel(
            name='StagingFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=userdefinedmodel.models.node.UUIDFilenameUploadTo('staging'))),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('intended_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdefinedmodel.fielddefinition')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_files', to=settings.AUTH_USER_MODEL)),
                ('intended_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdefinedmodel.userdefinedmodelentitynode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('value_bool', models.BooleanField(null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_time', models.TimeField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='', max_length=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='userdefinedmodel.fielddefinition')),
                ('value_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('value_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('value_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='userdefinedmodel.fileattachment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='userdefinedmodel.userdefinedmodelentitynode')),
                ('value_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='userdefinedmodel.userdefinedmodelentitynode')),
            ],
        ),
        migrations.CreateModel(
            name='FieldEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_kind', models.CharField(choices=[('field_value', 'Field Value'), ('node_added', 'Node Added'), ('node_removed', 'Node Removed'), ('node_reordered', 'Node Reordered'), ('node_transition', 'Node Transition')], default='field_value', max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdefinedmodel.fielddefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_edits', to='userdefinedmodel.editgroup')),
                ('new_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_new_in_edits', to='userdefinedmodel.fileattachment')),
                ('old_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_old_in_edits', to='userdefinedmodel.fileattachment')),
                ('affected_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='userdefinedmodel.userdefinedmodelentitynode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldDefaultValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('value_bool', models.BooleanField(null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_time', models.TimeField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='', max_length=10)),
                ('value_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('value_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='userdefinedmodel.fielddefinition')),
                ('value_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='userdefinedmodel.fileattachment')),
                ('value_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='userdefinedmodel.userdefinedmodelentitynode')),
            ],
        ),
        migrations.AddField(
            model_name='editgroup',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_groups', to='userdefinedmodel.userdefinedmodelentitynode'),
        ),
        migrations.CreateModel(
            name='UserDefinedModelEntityMigration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('bulk_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_migrations', to='userdefinedmodel.bulkmigrationplan')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.configversion')),
                ('target_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.configversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MigrationFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('map', 'Map'), ('discard', 'Discard')], max_length=10)),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.fielddefinition')),
                ('target_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.fielddefinition')),
                ('migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='userdefinedmodel.userdefinedmodelentitymigration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDefinedModelType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('field_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_defined_model_types', to='userdefinedmodel.fieldconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userdefinedmodelentitymigration',
            name='target_user_defined_model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_entity_migrations', to='userdefinedmodel.userdefinedmodeltype'),
        ),
        migrations.AddField(
            model_name='bulkmigrationplan',
            name='user_defined_model_type_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='userdefinedmodel.userdefinedmodeltype'),
        ),
        migrations.CreateModel(
            name='UserDefinedModelTypePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_assignments', to='userdefinedmodel.policy')),
                ('user_defined_model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_policies', to='userdefinedmodel.userdefinedmodeltype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='userdefinedmodeltype',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='user_defined_model_types', through='userdefinedmodel.UserDefinedModelTypePolicy', to='userdefinedmodel.policy'),
        ),
        migrations.AddField(
            model_name='configversion',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_versions', to='userdefinedmodel.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_initial', models.BooleanField(default=False)),
                ('allows_edit', models.BooleanField(default=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='userdefinedmodel.workflowdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='userdefinedmodelentitynode',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes_in_state', to='userdefinedmodel.workflowstate'),
        ),
        migrations.CreateModel(
            name='WorkflowStateTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='userdefinedmodel.workflowstate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='userdefinedmodel.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='userdefinedmodel.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='userdefinedmodel.workflowdefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transitionaction',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='userdefinedmodel.workflowtransition'),
        ),
        migrations.CreateModel(
            name='WorkflowTransitionTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=200)),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='userdefinedmodel.workflowtransition')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedMimeTypeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_types', to='userdefinedmodel.allowedmimetypesrule')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='userdefinedmodel.fieldconfig')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('config', 'code'), name='unique_language_per_config'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('config',), name='one_default_language_per_config')],
            },
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(fields=('version', 'slug'), name='unique_slug_in_version'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinitiontranslation',
            constraint=models.UniqueConstraint(fields=('field', 'language'), name='unique_label_translation_per_field_language'),
        ),
        migrations.AddConstraint(
            model_name='multifieldruleassociation',
            constraint=models.UniqueConstraint(fields=('rule', 'field'), name='unique_field_per_multi_rule'),
        ),
        migrations.AddField(
            model_name='userdefinedmodelentitymigration',
            name='user_defined_model_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='userdefinedmodel.userdefinedmodelentity'),
        ),
        migrations.AddField(
            model_name='userdefinedmodelentity',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='edited_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefinedmodelentity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefinedmodelentity',
            name='user_defined_model_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='userdefinedmodel.userdefinedmodeltype'),
        ),
        migrations.AddField(
            model_name='editgroup',
            name='root_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_edit_groups', to='userdefinedmodel.userdefinedmodelentity'),
        ),
        migrations.AddConstraint(
            model_name='fieldvalue',
            constraint=models.UniqueConstraint(fields=('node', 'field', 'language'), name='unique_value_per_node_field_language'),
        ),
        migrations.AddConstraint(
            model_name='fielddefaultvalue',
            constraint=models.UniqueConstraint(fields=('field', 'language'), name='unique_default_per_field_language'),
        ),
        migrations.AddConstraint(
            model_name='userdefinedmodeltypepolicy',
            constraint=models.UniqueConstraint(fields=('user_defined_model_type', 'policy'), name='unique_policy_per_type'),
        ),
        migrations.AddConstraint(
            model_name='configversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('config',), name='unique_draft_per_config'),
        ),
        migrations.AddConstraint(
            model_name='configversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('config',), name='unique_published_per_config'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('workflow',), name='one_initial_state_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'name'), name='unique_state_name_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowstatetranslation',
            constraint=models.UniqueConstraint(fields=('state', 'language'), name='unique_state_translation_per_language'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransitiontranslation',
            constraint=models.UniqueConstraint(fields=('transition', 'language'), name='unique_transition_translation_per_language'),
        ),
        migrations.AddConstraint(
            model_name='allowedmimetypeentry',
            constraint=models.UniqueConstraint(fields=('rule', 'mime_type'), name='unique_mime_per_rule'),
        ),
    ]
