# Generated by Django 6.0.4 on 2026-06-01 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0013_fieldedit_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMigrationSubmodelMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodel_mappings', to='userdefinedmodel.bulkmigrationplan')),
                ('source_parent_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.fielddefinition')),
                ('target_submodel_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.configversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkMigrationSubmodelFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('map', 'Map'), ('discard', 'Discard')], max_length=10)),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.fielddefinition')),
                ('target_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userdefinedmodel.fielddefinition')),
                ('submodel_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='userdefinedmodel.bulkmigrationsubmodelmapping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkMigrationWorkflowStateMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_slug', models.CharField(max_length=80)),
                ('from_state', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state_mappings', to='userdefinedmodel.bulkmigrationplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
