# Generated by Django 6.0.4 on 2026-06-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0017_add_structural_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='data_type',
            field=models.CharField(choices=[('text_short', 'Text Short'), ('text_long', 'Text Long'), ('text_markdown', 'Text Markdown'), ('text_richtext', 'Text Richtext'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime'), ('select_single', 'Select Single'), ('select_multi', 'Select Multi'), ('image', 'Image'), ('file', 'File'), ('user_select', 'User Select'), ('user_select_multi', 'User Select Multi'), ('group_select', 'Group Select'), ('group_select_multi', 'Group Select Multi'), ('submodel_select', 'Submodel Select'), ('submodel_list', 'Submodel List'), ('entity_select', 'Entity Select'), ('entity_select_multi', 'Entity Select Multi'), ('slug_id', 'Slug Id'), ('workflow', 'Workflow'), ('tab_container', 'Tab Container'), ('tab', 'Tab'), ('save_button', 'Save Button'), ('hstack', 'Hstack'), ('hstack_group', 'Hstack Group'), ('tab_prev', 'Tab Prev'), ('tab_next', 'Tab Next')], max_length=30),
        ),
    ]
