# Generated by Django 6.0.4 on 2026-07-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0024_fieldedit_policy_action_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='submodel_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_as_submodel', to='userdefinedmodel.configversion'),
        ),
        migrations.AlterField(
            model_name='userdefinedmodelentity',
            name='user_defined_model_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='userdefinedmodel.userdefinedmodeltype'),
        ),
    ]
