# Generated by Django 6.0.4 on 2026-07-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0025_alter_fielddefinition_submodel_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtransition',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
