# Generated by Django 6.0.4 on 2026-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0027_split_form_tree_and_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmigrationplan',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
