# Generated by Django 6.0.4 on 2026-08-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0030_drop_overflow_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldedit',
            name='affected_node_summary',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
