# Generated by Django 6.0.4 on 2026-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0031_fieldedit_affected_node_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelement',
            name='element_type',
            field=models.CharField(choices=[('field', 'Field'), ('tab_container', 'Tab Container'), ('tab', 'Tab'), ('save_button', 'Save Button'), ('hstack', 'Hstack'), ('hstack_group', 'Hstack Group'), ('tab_prev', 'Tab Prev'), ('tab_next', 'Tab Next'), ('date_range', 'Date Range'), ('markdown_display', 'Markdown Display'), ('backlink_list', 'Backlink List')], max_length=30),
        ),
    ]
