# Generated by Django 6.0.4 on 2026-08-08 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0032_alter_formelement_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelement',
            name='element_type',
            field=models.CharField(choices=[('field', 'Field'), ('tab_container', 'Tab Container'), ('tab', 'Tab'), ('save_button', 'Save Button'), ('hstack', 'Hstack'), ('hstack_group', 'Hstack Group'), ('tab_prev', 'Tab Prev'), ('tab_next', 'Tab Next'), ('date_range', 'Date Range'), ('markdown_display', 'Markdown Display'), ('backlink_list', 'Backlink List'), ('sync_status', 'Sync Status')], max_length=30),
        ),
        migrations.CreateModel(
            name='TypeEditorTabConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab_id', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('config_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_editor_tab_configs', to='userdefinedmodel.configversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('config_version', 'tab_id'), name='unique_tab_config_per_version')],
            },
        ),
    ]
