# Generated by Django 6.0.4 on 2026-08-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_pretix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpretixsyncitem',
            name='remote_identity',
            field=models.JSONField(blank=True, default=None, help_text='events-and-sync.md §14: {"organizer_slug", "event_slug", "subevent_id"} pinned at first successful push via the parent_event binding path. Every later push/pull/delete uses this, never re-resolving parent_event — so a later change to what parent_event resolves to does not move an already-created subevent (see compute_drift for the surfaced mismatch). Null for items still on the legacy area_association path.', null=True, verbose_name='Remote identity'),
        ),
        migrations.AddField(
            model_name='pretixsyncitem',
            name='remote_identity',
            field=models.JSONField(blank=True, default=None, help_text='events-and-sync.md §14: {"organizer_slug", "event_slug", "subevent_id"} pinned at first successful push via the parent_event binding path. Every later push/pull/delete uses this, never re-resolving parent_event — so a later change to what parent_event resolves to does not move an already-created subevent (see compute_drift for the surfaced mismatch). Null for items still on the legacy area_association path.', null=True, verbose_name='Remote identity'),
        ),
    ]
