# Generated by Django 6.0.4 on 2026-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_pretix', '0003_backfill_remote_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretixsynctargetareaassociation',
            name='sync_target',
        ),
        migrations.RemoveField(
            model_name='pretixsyncitem',
            name='area_association',
        ),
        migrations.RemoveField(
            model_name='historicalpretixsyncitem',
            name='area_association',
        ),
        migrations.AlterField(
            model_name='historicalpretixsyncitem',
            name='remote_identity',
            field=models.JSONField(blank=True, default=None, help_text='events-and-sync.md §14: {"organizer_slug", "event_slug", "subevent_id"} pinned at first successful push via the parent_event binding. Every later push/pull/delete uses this, never re-resolving parent_event — so a later change to what parent_event resolves to does not move an already-created subevent (see compute_drift for the surfaced mismatch). Null until the first successful push.', null=True, verbose_name='Remote identity'),
        ),
        migrations.AlterField(
            model_name='pretixsyncitem',
            name='remote_identity',
            field=models.JSONField(blank=True, default=None, help_text='events-and-sync.md §14: {"organizer_slug", "event_slug", "subevent_id"} pinned at first successful push via the parent_event binding. Every later push/pull/delete uses this, never re-resolving parent_event — so a later change to what parent_event resolves to does not move an already-created subevent (see compute_drift for the surfaced mismatch). Null until the first successful push.', null=True, verbose_name='Remote identity'),
        ),
        migrations.DeleteModel(
            name='HistoricalPretixSyncTargetAreaAssociation',
        ),
        migrations.DeleteModel(
            name='PretixSyncTargetAreaAssociation',
        ),
    ]
