// Import all editor files — side effects register each editor with the global registry
import './TextShortEditor'
import './TextLongEditor'
import './TextMarkdownEditor'
import './TextRichtextEditor'
import './SlugIdEditor'
import './NumberEditor'
import './BooleanEditor'
import './DateTimeEditors'
import './SelectSingleEditor'
import './SelectMultiEditor'
import './UserSelectEditor'
import './GroupSelectEditor'
import './EntitySelectEditor'
import './FileEditor'
import './WorkflowCellEditor'
import './SubmodelEditor'
import './DateRangeEditor'

// Import all preview renderer files — side effects register each renderer with the preview registry
import './TextPreview'
import './TextMarkdownPreview'
import './TextRichtextPreview'
import './BooleanPreview'
import './NumberPreview'
import './SlugIdPreview'
import './DateTimePreview'
import './SelectSinglePreview'
import './SelectMultiPreview'
import './UserSelectPreview'
import './GroupSelectPreview'
import './EntitySelectPreview'
import './FilePreview'
import './WorkflowPreview'
import './SubmodelPreview'

export { fieldEditorRegistry } from './registry'
export { FieldInput } from './FieldInput'
export type { FieldInputProps } from './types'
export { getLang } from './types'
export { PolicyMessageList, SeverityIndicator } from './shared'
export { fieldPreviewRegistry } from './registry-preview'
export { FieldPreview, fieldPreviewText } from './FieldPreview'
export type { PreviewProps } from './FieldPreview'
export { PreviewTable } from './PreviewTable'
export type { PreviewRow } from './PreviewTable'
export { EntityCombobox } from './EntityCombobox'
export type { EntityComboboxProps } from './EntityCombobox'
export { BacklinkListPreview } from './BacklinkListPreview'
export type { BacklinkListPreviewProps } from './BacklinkListPreview'
export { CalendarPreview } from './CalendarPreview'
export type { CalendarPreviewProps } from './CalendarPreview'
