# Generated by Django 6.0.7 on 2026-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0016_add_delete_review_proposal_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproposal',
            name='photo_alt_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='proposal',
            name='photo_alt_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
