# Generated by Django 6.0.7 on 2026-10-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0017_proposal_photo_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmissiontype',
            name='auto_calculate_prices',
            field=models.BooleanField(default=False, help_text='If enabled, calculated prices are created automatically for an event as soon as the event is created for a proposal of this submission type.', verbose_name='Preise automatisch berechnen'),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='auto_calculate_prices',
            field=models.BooleanField(default=False, help_text='If enabled, calculated prices are created automatically for an event as soon as the event is created for a proposal of this submission type.', verbose_name='Preise automatisch berechnen'),
        ),
    ]
