# Generated by Django 6.0.7 on 2026-10-01 14:37

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0018_historicalsubmissiontype_auto_calculate_prices_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalreview',
            name='is_blocking',
            field=models.BooleanField(default=True, help_text='If disabled, this review is optional: it is still requested and shown, but it does not block acceptance of the proposal.', verbose_name='Blocks acceptance'),
        ),
        migrations.CreateModel(
            name='HistoricalProposalAreaReviewGroup',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_blocking', models.BooleanField(default=True, help_text='If disabled, the automatically requested review is optional: it is requested and shown, but it does not block acceptance.', verbose_name='Blocks acceptance')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apiv1.proposalarea')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Automatic area review request',
                'verbose_name_plural': 'historical Automatic area review requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProposalAreaReviewGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_blocking', models.BooleanField(default=True, help_text='If disabled, the automatically requested review is optional: it is requested and shown, but it does not block acceptance.', verbose_name='Blocks acceptance')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_group_mappings', to='apiv1.proposalarea')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_area_review_mappings', to='auth.group')),
            ],
            options={
                'verbose_name': 'Automatic area review request',
                'verbose_name_plural': 'Automatic area review requests',
                'ordering': ['area__sort_order', 'group__name'],
                'constraints': [models.UniqueConstraint(fields=('area', 'group'), name='unique_area_review_group')],
            },
        ),
    ]
