/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/udm/bulk-migrations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Bulk Migration */
        post: operations["userdefinedmodel_api_bundle_create_bulk_migration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/bulk-migrations/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Migration Preview */
        post: operations["userdefinedmodel_api_bundle_bulk_migration_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/bulk-migrations/{plan_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bulk Migration */
        get: operations["userdefinedmodel_api_bundle_get_bulk_migration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/bulk-migrations/{plan_id}/execute/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Bulk Migration Plan */
        post: operations["userdefinedmodel_api_bundle_execute_bulk_migration_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/config-versions/{version_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config Version
         * @description Fetch a single config version by id (any status). Used to render an
         *     entity's form against its actual pinned version, even when archived.
         */
        get: operations["userdefinedmodel_api_configs_get_config_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Configs */
        get: operations["userdefinedmodel_api_configs_list_configs"];
        put?: never;
        /** Create Config */
        post: operations["userdefinedmodel_api_configs_create_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["userdefinedmodel_api_configs_get_config"];
        put?: never;
        post?: never;
        /** Delete Config */
        delete: operations["userdefinedmodel_api_configs_delete_config"];
        options?: never;
        head?: never;
        /** Update Config */
        patch: operations["userdefinedmodel_api_configs_update_config"];
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Config Versions */
        get: operations["userdefinedmodel_api_configs_list_config_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft Version */
        get: operations["userdefinedmodel_api_configs_get_draft_version"];
        /** Replace Draft */
        put: operations["userdefinedmodel_api_configs_replace_draft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/draft/as-input/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draft As Input
         * @description Return the draft config version in ConfigDraftIn shape for round-trip editing.
         */
        get: operations["userdefinedmodel_api_configs_get_draft_as_input"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/draft/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Draft */
        post: operations["userdefinedmodel_api_configs_publish_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/published/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Published Version */
        get: operations["userdefinedmodel_api_configs_get_published_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description List entities for a single UDM type, filtered to those the user may view.
         *     Field values are reduced to the viewable set per entity (policy-enforced).
         */
        get: operations["userdefinedmodel_api_entities_list_entities"];
        put?: never;
        /** Create Entity */
        post: operations["userdefinedmodel_api_entities_create_entity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["userdefinedmodel_api_entities_get_entity"];
        put?: never;
        post?: never;
        /** Delete Entity */
        delete: operations["userdefinedmodel_api_entities_delete_entity"];
        options?: never;
        head?: never;
        /** Patch Entity */
        patch: operations["userdefinedmodel_api_entities_patch_entity"];
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity History */
        get: operations["userdefinedmodel_api_entities_entity_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/migrate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Migration */
        post: operations["userdefinedmodel_api_entities_execute_migration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/migration-preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Migration Preview
         * @description Side-effect-free migration preview: the migration record is created by
         *     the execute endpoint, so refreshes/retries of this GET write nothing.
         */
        get: operations["userdefinedmodel_api_entities_migration_preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/policy-document/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Policy Document */
        get: operations["userdefinedmodel_api_entities_entity_policy_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/transition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition Entity
         * @description Apply pending edits (if any) and execute the transition ATOMICALLY: the
         *     policy evaluates the patched, not-yet-committed state against the persisted
         *     pre-patch snapshot, and a denial rolls back the edits with the transition —
         *     they are never persisted on their own (review §4, execution semantics).
         */
        post: operations["userdefinedmodel_api_entities_transition_entity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/validation-preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validation Preview
         * @description ONE preview request replacing the removed validate_only modes (§4):
         *     applies the pending edits in a rolled-back transaction, runs a single
         *     'preview' policy evaluation, and returns the save verdict, all messages,
         *     and the per-node per-workflow-field valid-transition matrix.
         */
        post: operations["userdefinedmodel_api_entities_validation_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entity-search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Entities */
        get: operations["userdefinedmodel_api_autocomplete_search_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/export-bundle-zip/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Bundle Zip
         * @description Export a ZIP bundle: UDM_BUNDLE.json + policies/<slug>.rego for each policy.
         */
        post: operations["userdefinedmodel_api_bundle_export_bundle_zip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Groups */
        get: operations["userdefinedmodel_api_autocomplete_search_groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/import-bundle-zip/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Bundle Zip
         * @description Import a ZIP bundle (UDM_BUNDLE.json + policies/*.rego).
         *
         *     scope_type_ids: comma-separated UUID strings of in-scope UDM Types.
         *     policy_slug: if set, save each policy rego with its own slug (already done from policies/ dir).
         */
        post: operations["userdefinedmodel_api_bundle_import_bundle_zip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/parse-bundle-zip/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Bundle Zip
         * @description Parse a ZIP bundle and return the scope_type_ids and udm_types metadata it declares.
         */
        post: operations["userdefinedmodel_api_bundle_parse_bundle_zip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/policies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["userdefinedmodel_api_policies_list_policies"];
        put?: never;
        /** Create Policy */
        post: operations["userdefinedmodel_api_policies_create_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/policies/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["userdefinedmodel_api_policies_get_policy"];
        /** Update Policy */
        put: operations["userdefinedmodel_api_policies_update_policy"];
        post?: never;
        /** Delete Policy */
        delete: operations["userdefinedmodel_api_policies_delete_policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/staging-files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Staging File */
        post: operations["userdefinedmodel_api_staging_upload_staging_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/staging-files/{staging_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Staging File */
        delete: operations["userdefinedmodel_api_staging_delete_staging_file"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Udm Types */
        get: operations["userdefinedmodel_api_types_list_udm_types"];
        put?: never;
        /** Create Udm Type */
        post: operations["userdefinedmodel_api_types_create_udm_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Udm Type */
        get: operations["userdefinedmodel_api_types_get_udm_type"];
        put?: never;
        post?: never;
        /** Delete Udm Type */
        delete: operations["userdefinedmodel_api_types_delete_udm_type"];
        options?: never;
        head?: never;
        /** Update Udm Type */
        patch: operations["userdefinedmodel_api_types_update_udm_type"];
        trace?: never;
    };
    "/api/udm/types/{type_id}/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Type Config */
        get: operations["userdefinedmodel_api_types_get_type_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/eval-policy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Policy For Type
         * @description Evaluate the Rego policy for a given entity + user and return the full
         *     input document, the raw policy sources, and the structured output.
         *
         *     ``action`` accepts every entity action of the policy contract, including
         *     ``browse`` and ``create``. For ``transition``, ``node_id`` selects the
         *     target node (a submodel node of the entity, or the entity itself when
         *     omitted); the transition is resolved against that node's own schema.
         */
        get: operations["userdefinedmodel_api_types_eval_policy_for_type"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/eval-policy/nodes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Policy Nodes
         * @description The full node tree of an entity for the policy evaluator's node picker,
         *     with each node's workflow fields and their transition names.
         *
         *     Deliberately bypasses the entity view policy: evaluator users (policy
         *     admins / superusers) must be able to target submodel nodes they could not
         *     browse themselves. Gated like eval-policy itself.
         */
        get: operations["userdefinedmodel_api_types_eval_policy_nodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/policies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Policies */
        get: operations["userdefinedmodel_api_types_list_type_policies"];
        put?: never;
        /** Assign Policy */
        post: operations["userdefinedmodel_api_types_assign_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/policies/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Policy */
        delete: operations["userdefinedmodel_api_types_remove_policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/public-fields/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Type Public Fields
         * @description Evaluate data.udm.public_type_fields from the type's policies.
         *
         *     Runs all policies for this type with a minimal input
         *     (action=public_type_fields, no entity or user) and returns the resulting
         *     dict.  Returns an empty dict when no policies are attached or the rule is
         *     not defined.
         */
        get: operations["userdefinedmodel_api_types_get_type_public_fields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Users */
        get: operations["userdefinedmodel_api_autocomplete_search_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/workflows/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["userdefinedmodel_api_workflows_list_workflows"];
        put?: never;
        /** Create Workflow */
        post: operations["userdefinedmodel_api_workflows_create_workflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/workflows/{workflow_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["userdefinedmodel_api_workflows_get_workflow"];
        /** Update Workflow */
        put: operations["userdefinedmodel_api_workflows_update_workflow"];
        post?: never;
        /** Delete Workflow */
        delete: operations["userdefinedmodel_api_workflows_delete_workflow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/workflows/{workflow_id}/state-counts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workflow State Counts
         * @description Return a dict of state_name → entity count for fields using this workflow.
         */
        get: operations["userdefinedmodel_api_workflows_workflow_state_counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/workflows/{workflow_id}/versions/draft/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Workflow Draft */
        post: operations["userdefinedmodel_api_workflows_publish_workflow_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulkMigrationCreateIn */
        BulkMigrationCreateIn: {
            /** Field Mappings */
            field_mappings: components["schemas"]["MigrationFieldMappingIn"][];
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Submodel Mappings */
            submodel_mappings?: components["schemas"]["SubmodelMigrationIn"][];
            /**
             * Target Version Id
             * Format: uuid
             */
            target_version_id: string;
            /** User Defined Model Type Filter Id */
            user_defined_model_type_filter_id?: string | null;
            /** Workflow State Mappings */
            workflow_state_mappings?: components["schemas"]["WorkflowFieldStateMappingIn"][];
        };
        /** BulkMigrationOut */
        BulkMigrationOut: {
            /** Done Entities */
            done_entities: number;
            /**
             * Error Message
             * @default
             */
            error_message: string;
            /** Executed At */
            executed_at: string | null;
            /** Failed Entities */
            failed_entities: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            status: components["schemas"]["BulkMigrationStatus"];
            /**
             * Target Version Id
             * Format: uuid
             */
            target_version_id: string;
            /** Total Entities */
            total_entities: number;
            /** User Defined Model Type Filter Id */
            user_defined_model_type_filter_id: string | null;
        };
        /**
         * BulkMigrationStatus
         * @enum {string}
         */
        BulkMigrationStatus: "draft" | "running" | "done" | "partial";
        /** BundleExportIn */
        BundleExportIn: {
            /** Scope Type Ids */
            scope_type_ids: string[];
        };
        /**
         * ConfigDraftExportOut
         * @description ConfigVersion serialised in ConfigDraftIn shape for round-trip export.
         */
        ConfigDraftExportOut: {
            /** Data Fields */
            data_fields?: components["schemas"]["FieldDefinitionDraftOut"][];
            /** Fields */
            fields?: components["schemas"]["FieldDefinitionDraftOut"][] | null;
            /** Form Elements */
            form_elements?: components["schemas"]["FormElementDraftOut"][];
            /** Notes */
            notes: string;
        };
        /** ConfigDraftIn */
        ConfigDraftIn: {
            /** Data Fields */
            data_fields?: components["schemas"]["FieldDefinitionIn"][];
            /** Fields */
            fields?: components["schemas"]["FieldDefinitionIn"][] | null;
            /** Form Elements */
            form_elements?: components["schemas"]["FormElementIn"][];
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ConfigLanguageIn */
        ConfigLanguageIn: {
            /** Code */
            code: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Label */
            label: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** ConfigLanguageOut */
        ConfigLanguageOut: {
            /** Code */
            code: string;
            /** Is Default */
            is_default: boolean;
            /** Label */
            label: string;
            /** Sort Order */
            sort_order: number;
        };
        /** ConfigVersionOut */
        ConfigVersionOut: {
            /** Data Fields */
            data_fields: components["schemas"]["FieldDefinitionOut"][];
            /** Fields */
            fields: components["schemas"]["FieldDefinitionOut"][];
            /** Form Elements */
            form_elements: components["schemas"]["FormElementOut"][];
            /** Languages */
            languages: components["schemas"]["ConfigLanguageOut"][];
            /** Notes */
            notes: string;
            /** Published At */
            published_at: string | null;
            /** Status */
            status: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /** DashboardColumnOut */
        DashboardColumnOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Renderer */
            renderer: string;
            /** Value */
            value?: unknown;
        };
        /**
         * DataType
         * @enum {string}
         */
        DataType: "text_short" | "text_long" | "text_markdown" | "text_richtext" | "integer" | "float" | "boolean" | "date" | "time" | "datetime" | "select_single" | "select_multi" | "image" | "file" | "user_select" | "user_select_multi" | "group_select" | "group_select_multi" | "submodel_select" | "submodel_list" | "entity_select" | "entity_select_multi" | "slug_id" | "workflow" | "tab_container" | "tab" | "save_button" | "hstack" | "hstack_group" | "tab_prev" | "tab_next";
        /** EditGroupOut */
        EditGroupOut: {
            /** Edits */
            edits: components["schemas"]["FieldEditOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Node Type */
            node_type: string;
            /** Saved At */
            saved_at: string;
            saved_by: components["schemas"]["UserRefOut"] | null;
        };
        /** EditHistoryOut */
        EditHistoryOut: {
            /** Count */
            count: number;
            /** Next */
            next: string | null;
            /** Results */
            results: components["schemas"]["EditGroupOut"][];
        };
        /** EntityAutocompleteItem */
        EntityAutocompleteItem: {
            /** Display */
            display: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type Id */
            type_id: string | null;
        };
        /** EntityCreateIn */
        EntityCreateIn: {
            /**
             * User Defined Model Type Id
             * Format: uuid
             */
            user_defined_model_type_id: string;
        };
        /** EntityOut */
        EntityOut: {
            /** Children */
            children: {
                [key: string]: unknown[];
            };
            /**
             * Config Version Id
             * Format: uuid
             */
            config_version_id: string;
            /**
             * Creatable Submodels
             * @default {}
             */
            creatable_submodels: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Created At */
            created_at: string;
            /**
             * Dashboard Columns
             * @default []
             */
            dashboard_columns: components["schemas"]["DashboardColumnOut"][];
            /**
             * Deletable Nodes
             * @default []
             */
            deletable_nodes: string[];
            /**
             * Editable Fields
             * @default {}
             */
            editable_fields: {
                [key: string]: string[];
            };
            /** Field Values */
            field_values: components["schemas"]["FieldValueOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Overflow Data */
            overflow_data: {
                [key: string]: unknown;
            };
            /**
             * Policy Messages
             * @default []
             */
            policy_messages: unknown[];
            /** Updated At */
            updated_at: string;
            /** User Defined Model Type Id */
            user_defined_model_type_id: string | null;
            /**
             * Viewable Fields
             * @default {}
             */
            viewable_fields: {
                [key: string]: string[];
            };
        };
        /** EntityPatchIn */
        EntityPatchIn: {
            /** Changed Fields */
            changed_fields: {
                [key: string]: unknown;
            };
        };
        /**
         * EvalNodeOut
         * @description One node of an entity tree, as offered by the policy evaluator's node
         *     picker. Includes submodel nodes the requesting admin may not otherwise view.
         */
        EvalNodeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Parent Field Slug */
            parent_field_slug?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Workflow Fields
             * @default []
             */
            workflow_fields: components["schemas"]["EvalWorkflowFieldOut"][];
        };
        /**
         * EvalWorkflowFieldOut
         * @description A workflow field on a node in the evaluator's node tree.
         */
        EvalWorkflowFieldOut: {
            /** Slug */
            slug: string;
            /** Transitions */
            transitions: string[];
        };
        /** FieldConfigCreateIn */
        FieldConfigCreateIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Languages */
            languages: components["schemas"]["ConfigLanguageIn"][];
            /** Name */
            name: string;
        };
        /** FieldConfigOut */
        FieldConfigOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Entity Count */
            entity_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Languages */
            languages: components["schemas"]["ConfigLanguageOut"][];
            /** Last Published At */
            last_published_at: string | null;
            /** Name */
            name: string;
            /** Published Submodel Usage Count */
            published_submodel_usage_count: number;
            /** Stale Entity Count */
            stale_entity_count: number;
            /** Type Ids */
            type_ids: string[];
            /** Version Count */
            version_count: number;
        };
        /** FieldConfigUpdateIn */
        FieldConfigUpdateIn: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * FieldDefinitionDraftOut
         * @description A DATA field serialised in the shape that FieldDefinitionIn accepts,
         *     so the output can be fed back into PUT .../draft/ without modification.
         */
        FieldDefinitionDraftOut: {
            /** Data Type */
            data_type: string;
            /** Default */
            default?: unknown | null;
            /** Is Localized */
            is_localized: boolean;
            /** Slug */
            slug: string;
            /** Submodel Config Version Id */
            submodel_config_version_id?: string | null;
            /** Type Config */
            type_config: {
                [key: string]: unknown;
            };
            /** Workflow Definition Id */
            workflow_definition_id?: string | null;
            /** Workflow Version Id */
            workflow_version_id?: string | null;
        };
        /**
         * FieldDefinitionIn
         * @description A DATA field definition (storage semantics only). Form-tree concerns
         *     (sort_order, is_preview, parent, labels) live on FormElementIn.
         *     Backward-compat: kept under the FieldDefinitionIn name for the API shape.
         *     Legacy fields (sort_order, is_preview, parent_slug, labels, help_texts) are
         *     accepted for round-trip with old clients but ignored — they belong to the
         *     bound FormElement, which replace_draft creates 1:1 from them in legacy mode.
         */
        FieldDefinitionIn: {
            data_type: components["schemas"]["DataType"];
            /** Default */
            default?: unknown | null;
            /** Help Texts */
            help_texts?: {
                [key: string]: string;
            } | null;
            /**
             * Is Localized
             * @default false
             */
            is_localized: boolean;
            /** Is Preview */
            is_preview?: boolean | null;
            /** Labels */
            labels?: {
                [key: string]: string;
            } | null;
            /** Parent Slug */
            parent_slug?: string | null;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order?: number | null;
            /** Submodel Config Version Id */
            submodel_config_version_id?: string | null;
            /** Type Config */
            type_config?: {
                [key: string]: unknown;
            };
            /** Workflow Definition Id */
            workflow_definition_id?: string | null;
            /** Workflow Version Id */
            workflow_version_id?: string | null;
        };
        /**
         * FieldDefinitionOut
         * @description A DATA field (storage semantics). The form-tree fields below are OPTIONAL
         *     and only populated in the backward-compat `ConfigVersionOut.fields` merge
         *     (which lifts them from the bound FormElement); they are absent on the
         *     canonical `data_fields` list.
         */
        FieldDefinitionOut: {
            /** Data Type */
            data_type: string;
            /** Default */
            default?: unknown | null;
            /** Help Text */
            help_text?: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Localized */
            is_localized: boolean;
            /**
             * Is Preview
             * @default false
             */
            is_preview: boolean;
            /** Label */
            label?: {
                [key: string]: string;
            };
            /** Parent Slug */
            parent_slug?: string | null;
            /** Slug */
            slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            submodel_config?: components["schemas"]["ConfigVersionOut"] | null;
            /** Type Config */
            type_config: {
                [key: string]: unknown;
            };
            workflow_version?: components["schemas"]["WorkflowVersionOut"] | null;
        };
        /** FieldEditOut */
        FieldEditOut: {
            /** Affected Node Id */
            affected_node_id?: string | null;
            /** Change Kind */
            change_kind: string;
            /** Field Label */
            field_label?: string | null;
            /** Field Slug */
            field_slug?: string | null;
            /**
             * Language
             * @default
             */
            language: string;
            /** New File Name */
            new_file_name?: string | null;
            /** New File Url */
            new_file_url?: string | null;
            /** New Value */
            new_value?: unknown | null;
            /** Old File Name */
            old_file_name?: string | null;
            /** Old File Url */
            old_file_url?: string | null;
            /** Old Value */
            old_value?: unknown | null;
        };
        /** FieldValueOut */
        FieldValueOut: {
            /** Data Type */
            data_type: string;
            /** Field Slug */
            field_slug: string;
            /**
             * Language
             * @default
             */
            language: string;
            /** Value */
            value: unknown;
        };
        /** FormElementBindingDraftOut */
        FormElementBindingDraftOut: {
            /** Data Field Slug */
            data_field_slug: string;
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** FormElementBindingIn */
        FormElementBindingIn: {
            /** Data Field Slug */
            data_field_slug: string;
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** FormElementBindingOut */
        FormElementBindingOut: {
            /** Data Field Slug */
            data_field_slug: string;
            /**
             * Role
             * @default
             */
            role: string;
        };
        /**
         * FormElementDraftOut
         * @description A FormElement serialised in the shape that FormElementIn accepts.
         */
        FormElementDraftOut: {
            /** Bindings */
            bindings?: components["schemas"]["FormElementBindingDraftOut"][];
            /** Element Type */
            element_type: string;
            /** Help Texts */
            help_texts: {
                [key: string]: string;
            };
            /** Is Preview */
            is_preview: boolean;
            /** Labels */
            labels?: {
                [key: string]: string;
            } | null;
            /** Parent Slug */
            parent_slug?: string | null;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /** Type Config */
            type_config: {
                [key: string]: unknown;
            };
        };
        /**
         * FormElementIn
         * @description A form-tree element: a structural control or a widget bound to one or
         *     more data fields. Labels/help_text live here (B1).
         */
        FormElementIn: {
            /** Bindings */
            bindings?: components["schemas"]["FormElementBindingIn"][];
            /** Element Type */
            element_type: string;
            /** Help Texts */
            help_texts?: {
                [key: string]: string;
            };
            /**
             * Is Preview
             * @default false
             */
            is_preview: boolean;
            /** Labels */
            labels?: {
                [key: string]: string;
            } | null;
            /** Parent Slug */
            parent_slug?: string | null;
            /** Slug */
            slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Type Config */
            type_config?: {
                [key: string]: unknown;
            };
        };
        /**
         * FormElementOut
         * @description A form-tree element (structural control or widget bound to data fields).
         */
        FormElementOut: {
            /** Bindings */
            bindings?: components["schemas"]["FormElementBindingOut"][];
            /** Element Type */
            element_type: string;
            /** Help Text */
            help_text: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Preview */
            is_preview: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Parent Slug */
            parent_slug?: string | null;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /** Type Config */
            type_config: {
                [key: string]: unknown;
            };
        };
        /** GroupAutocompleteItem */
        GroupAutocompleteItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * MigrationAction
         * @enum {string}
         */
        MigrationAction: "map" | "discard" | "overflow";
        /** MigrationExecuteIn */
        MigrationExecuteIn: {
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /** Field Mappings */
            field_mappings: components["schemas"]["MigrationFieldMappingIn"][];
            /** Target User Defined Model Type Id */
            target_user_defined_model_type_id?: string | null;
            /** Target Version Id */
            target_version_id?: string | null;
        };
        /** MigrationFieldMappingIn */
        MigrationFieldMappingIn: {
            action: components["schemas"]["MigrationAction"];
            /** Source Field Slug */
            source_field_slug: string;
            /** Target Field Slug */
            target_field_slug?: string | null;
        };
        /** MigrationPreviewFieldOut */
        MigrationPreviewFieldOut: {
            /** Conflict Reason */
            conflict_reason: string | null;
            /** Source Data Type */
            source_data_type: string;
            /** Source Slug */
            source_slug: string;
            suggested_action: components["schemas"]["MigrationAction"];
            /** Suggested Target Slug */
            suggested_target_slug: string | null;
        };
        /** MigrationPreviewOut */
        MigrationPreviewOut: {
            /** Field Previews */
            field_previews: components["schemas"]["MigrationPreviewFieldOut"][];
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Target Version Id
             * Format: uuid
             */
            target_version_id: string;
        };
        /** PolicyAssignIn */
        PolicyAssignIn: {
            /** Policy Slug */
            policy_slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** PolicyCreateIn */
        PolicyCreateIn: {
            /** Slug */
            slug: string;
            /** Source */
            source: string;
        };
        /** PolicyEvalOut */
        PolicyEvalOut: {
            /**
             * Coverage
             * @default []
             */
            coverage: {
                [key: string]: unknown;
            }[];
            /** Error */
            error?: string | null;
            /** Full Document */
            full_document?: {
                [key: string]: unknown;
            } | null;
            /** Input Document */
            input_document: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /** Policies */
            policies: {
                [key: string]: string;
            }[];
            /**
             * Prints
             * @default []
             */
            prints: string[];
            /**
             * Rule Errors
             * @default []
             */
            rule_errors: string[];
        };
        /** PolicyOut */
        PolicyOut: {
            /** Slug */
            slug: string;
            /** Source */
            source: string;
        };
        /** PolicyUpdateIn */
        PolicyUpdateIn: {
            /** Source */
            source: string;
        };
        /** StagingFileOut */
        StagingFileOut: {
            /** Expires At */
            expires_at: string;
            /** Mime Type */
            mime_type: string;
            /** Original Name */
            original_name: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Staging Id
             * Format: uuid
             */
            staging_id: string;
        };
        /** StateMigrationIn */
        StateMigrationIn: {
            /** From State */
            from_state: string;
            /** To State */
            to_state: string;
        };
        /**
         * SubmodelMigrationIn
         * @description Field mappings for child nodes under a single SUBMODEL_* field when the submodel version changed.
         */
        SubmodelMigrationIn: {
            /** Field Mappings */
            field_mappings?: components["schemas"]["MigrationFieldMappingIn"][];
            /** Source Parent Field Slug */
            source_parent_field_slug: string;
            /**
             * Target Submodel Version Id
             * Format: uuid
             */
            target_submodel_version_id: string;
        };
        /** TransitionIn */
        TransitionIn: {
            /** Changed Fields */
            changed_fields?: {
                [key: string]: unknown;
            };
            /** Field */
            field: string;
            /** Transition */
            transition: string;
        };
        /** TypePublicFieldsOut */
        TypePublicFieldsOut: {
            /** Descriptions */
            descriptions: {
                [key: string]: string;
            };
        };
        /** UDMTypeCreateIn */
        UDMTypeCreateIn: {
            /**
             * Label
             * @default
             */
            label: string;
            /** Name */
            name: string;
        };
        /** UDMTypeOut */
        UDMTypeOut: {
            /** Field Config Id */
            field_config_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** UDMTypeUpdateIn */
        UDMTypeUpdateIn: {
            /** Label */
            label?: string | null;
            /** Name */
            name?: string | null;
        };
        /** UserAutocompleteItem */
        UserAutocompleteItem: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** UserRefOut */
        UserRefOut: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** WorkflowCreateIn */
        WorkflowCreateIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** States */
            states: components["schemas"]["WorkflowStateIn"][];
            /** Transitions */
            transitions?: components["schemas"]["WorkflowTransitionIn"][];
            /** Virtual Node Positions */
            virtual_node_positions?: {
                [key: string]: unknown;
            };
        };
        /** WorkflowDefinitionOut */
        WorkflowDefinitionOut: {
            /** Created At */
            created_at?: string | null;
            /** Description */
            description: string;
            /** Draft Version Id */
            draft_version_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Initial State */
            initial_state: string | null;
            /** Last Edited At */
            last_edited_at?: string | null;
            /** Last Published At */
            last_published_at?: string | null;
            /** Name */
            name: string;
            /** Published Version Id */
            published_version_id?: string | null;
            /** States */
            states: components["schemas"]["WorkflowStateOut"][];
            /** Transitions */
            transitions: components["schemas"]["WorkflowTransitionOut"][];
            /** Virtual Node Positions */
            virtual_node_positions?: {
                [key: string]: unknown;
            };
        };
        /**
         * WorkflowFieldStateMappingIn
         * @description Explicit state name overrides for a single workflow field during bulk migration.
         */
        WorkflowFieldStateMappingIn: {
            /** Field Slug */
            field_slug: string;
            /** State Mappings */
            state_mappings?: components["schemas"]["StateMigrationIn"][];
        };
        /** WorkflowStateIn */
        WorkflowStateIn: {
            /**
             * Background Color
             * @default #ffffff
             */
            background_color: string;
            /**
             * Is Initial
             * @default false
             */
            is_initial: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /**
             * Position X
             * @default 0
             */
            position_x: number;
            /**
             * Position Y
             * @default 0
             */
            position_y: number;
            /** Previous Name */
            previous_name?: string | null;
        };
        /** WorkflowStateOut */
        WorkflowStateOut: {
            /**
             * Background Color
             * @default #ffffff
             */
            background_color: string;
            /** Is Initial */
            is_initial: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /** Position X */
            position_x: number;
            /** Position Y */
            position_y: number;
            /**
             * Text Color
             * @default #000000
             */
            text_color: string;
        };
        /** WorkflowTransitionIn */
        WorkflowTransitionIn: {
            /** From State */
            from_state?: string | null;
            /**
             * From Undefined Only
             * @default false
             */
            from_undefined_only: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
            /**
             * Source Handle
             * @default
             */
            source_handle: string;
            /**
             * Target Handle
             * @default
             */
            target_handle: string;
            /** To State */
            to_state: string;
        };
        /** WorkflowTransitionOut */
        WorkflowTransitionOut: {
            /** From State */
            from_state: string | null;
            /** From Undefined Only */
            from_undefined_only: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: unknown;
            };
            /** Source Handle */
            source_handle: string;
            /** Target Handle */
            target_handle: string;
            /** To State */
            to_state: string;
        };
        /** WorkflowUpdateIn */
        WorkflowUpdateIn: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** States */
            states?: components["schemas"]["WorkflowStateIn"][] | null;
            /** Transitions */
            transitions?: components["schemas"]["WorkflowTransitionIn"][] | null;
            /** Virtual Node Positions */
            virtual_node_positions?: {
                [key: string]: unknown;
            };
        };
        /**
         * WorkflowVersionOut
         * @description Workflow version content (states, transitions) with its own id.
         */
        WorkflowVersionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** States */
            states: components["schemas"]["WorkflowStateOut"][];
            /** Status */
            status: string;
            /** Transitions */
            transitions: components["schemas"]["WorkflowTransitionOut"][];
            /** Virtual Node Positions */
            virtual_node_positions?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    userdefinedmodel_api_bundle_create_bulk_migration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkMigrationCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkMigrationOut"];
                };
            };
        };
    };
    userdefinedmodel_api_bundle_bulk_migration_preview: {
        parameters: {
            query: {
                source_version_id: string;
                target_version_id: string;
                type_filter_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_bundle_get_bulk_migration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkMigrationOut"];
                };
            };
        };
    };
    userdefinedmodel_api_bundle_execute_bulk_migration_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_configs_get_config_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_list_configs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_configs_create_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldConfigCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_get_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_delete_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_configs_update_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldConfigUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_list_config_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_configs_get_draft_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_replace_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDraftIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_get_draft_as_input: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDraftExportOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_publish_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_configs_get_published_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_list_entities: {
        parameters: {
            query: {
                type_id: string;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_entities_create_entity: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_delete_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_entities_patch_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_entity_history: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditHistoryOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_execute_migration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationExecuteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_migration_preview: {
        parameters: {
            query?: {
                target_user_defined_model_type?: string | null;
                target_version?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationPreviewOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_entity_policy_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_entities_transition_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entities_validation_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_autocomplete_search_entities: {
        parameters: {
            query?: {
                q?: string;
                type_ids?: string[] | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityAutocompleteItem"][];
                };
            };
        };
    };
    userdefinedmodel_api_bundle_export_bundle_zip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleExportIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_autocomplete_search_groups: {
        parameters: {
            query?: {
                q?: string;
                ids?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupAutocompleteItem"][];
                };
            };
        };
    };
    userdefinedmodel_api_bundle_import_bundle_zip: {
        parameters: {
            query?: {
                scope_type_ids?: string;
                policy_slug?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_bundle_parse_bundle_zip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_policies_list_policies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_policies_create_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_policies_get_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_policies_update_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_policies_delete_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_staging_upload_staging_file: {
        parameters: {
            query?: {
                intended_field_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagingFileOut"];
                };
            };
        };
    };
    userdefinedmodel_api_staging_delete_staging_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staging_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_types_list_udm_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_types_create_udm_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UDMTypeCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"];
                };
            };
        };
    };
    userdefinedmodel_api_types_get_udm_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"];
                };
            };
        };
    };
    userdefinedmodel_api_types_delete_udm_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_types_update_udm_type: {
        parameters: {
            query?: {
                field_config_id?: string | null;
            };
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UDMTypeUpdateIn"] | null;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"];
                };
            };
        };
    };
    userdefinedmodel_api_types_get_type_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_types_eval_policy_for_type: {
        parameters: {
            query: {
                entity_id: string;
                user_id: string;
                action?: string;
                transition?: string | null;
                node_id?: string | null;
                sudo?: boolean;
            };
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyEvalOut"];
                };
            };
        };
    };
    userdefinedmodel_api_types_eval_policy_nodes: {
        parameters: {
            query: {
                entity_id: string;
            };
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalNodeOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_types_list_type_policies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_types_assign_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyAssignIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_types_remove_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_types_get_type_public_fields: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypePublicFieldsOut"];
                };
            };
        };
    };
    userdefinedmodel_api_autocomplete_search_users: {
        parameters: {
            query?: {
                q?: string;
                group_ids?: number[] | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAutocompleteItem"][];
                };
            };
        };
    };
    userdefinedmodel_api_workflows_list_workflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_workflows_create_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_workflows_get_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_workflows_update_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_workflows_delete_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_workflows_workflow_state_counts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_workflows_publish_workflow_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionOut"];
                };
            };
        };
    };
}
